### ISSUE TITLE
ip要是美国的？

### ISSUE THREAD

**Issue by duronxx** [mikumaycry/images#1]
chatgpt-next-web-1  | [Server Config] using 1 of 1 api key
chatgpt-next-web-1  | [Auth] use system api key
chatgpt-next-web-1  | [Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
chatgpt-next-web-1  | [Base Url] http://backend:8000
backend-1           | model='gpt-3.5-turbo' messages=[ChatMessage(role='system', content='\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2024/4/8 21:44:46\nLatex inline: $x^2$ \nLatex block: $$e=mc^2$$\n\n'), ChatMessage(role='user', content='我想让你担任机器学习工程师。我会写一些机器学习的概念，你的工作就是用通俗易懂的术语来解释它们。这可能包括提供构建模型的分步说明、给出所用的技术或者理论、提供评估函数等。我的问题是'), ChatMessage(role='user', content='hi')] temperature=1.0 top_p=1.0 max_length=None stream=True
backend-1           | INFO:     172.31.0.5:50498 - "POST /v1/chat/completions?path=v1&path=chat&path=completions HTTP/1.1" 200 OK
searxng-1           | 2024-04-08 13:44:45,093 ERROR:searx.engines.wikipedia: engine timeout
searxng-1           | 2024-04-08 13:44:45,093 ERROR:searx.engines.wikidata: engine timeout
searxng-1           | 2024-04-08 13:44:45,093 ERROR:searx.engines.duckduckgo: engine timeout
searxng-1           | 2024-04-08 13:44:45,093 ERROR:searx.engines.google: engine timeout
searxng-1           | 2024-04-08 13:44:45,093 ERROR:searx.engines.qwant: engine timeout
searxng-1           | 2024-04-08 13:44:45,093 ERROR:searx.engines.brave: engine timeout
freegpt35-1         | Request: POST /v1/chat/completions 1 messages (stream-enabled)
searxng-1           | 2024-04-08 13:44:45,225 WARNING:searx.engines.wikipedia: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'en.wikipedia.org')) False
searxng-1           | 2024-04-08 13:44:45,225 ERROR:searx.engines.wikipedia: HTTP requests timeout (search duration : 3.1328373439610004 s, timeout: 3.0 s) : ConnectTimeout
searxng-1           | 2024-04-08 13:44:45,228 WARNING:searx.engines.brave: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'search.brave.com')) False
searxng-1           | 2024-04-08 13:44:45,228 ERROR:searx.engines.brave: HTTP requests timeout (search duration : 3.135313393548131 s, timeout: 3.0 s) : ConnectTimeout
searxng-1           | 2024-04-08 13:44:45,229 WARNING:searx.engines.duckduckgo: ErrorContext('searx/engines/duckduckgo.py', 118, 'res = get(query_url)', 'httpx.ConnectTimeout', None, (None, None, 'duckduckgo.com')) False
searxng-1           | 2024-04-08 13:44:45,230 WARNING:searx.engines.qwant: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'api.qwant.com')) False
searxng-1           | 2024-04-08 13:44:45,230 ERROR:searx.engines.duckduckgo: HTTP requests timeout (search duration : 3.137855425477028 s, timeout: 3.0 s) : ConnectTimeout
searxng-1           | 2024-04-08 13:44:45,231 ERROR:searx.engines.qwant: HTTP requests timeout (search duration : 3.13800535351038 s, timeout: 3.0 s) : ConnectTimeout
searxng-1           | 2024-04-08 13:44:45,231 WARNING:searx.engines.google: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)",'httpx.ConnectTimeout', None, (None, None, 'www.google.com')) False
searxng-1           | 2024-04-08 13:44:45,231 ERROR:searx.engines.google: HTTP requests timeout (search duration : 3.138699973002076 s, timeout: 3.0 s) : ConnectTimeout
searxng-1           | 2024-04-08 13:44:45,294 WARNING:searx.engines.wikidata: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'query.wikidata.org')) False
searxng-1           | 2024-04-08 13:44:45,294 ERROR:searx.engines.wikidata: HTTP requests timeout (search duration : 3.2015139684081078 s, timeout: 3.0 s) : ConnectTimeout
freegpt35-1         | Error refreshing session ID, retrying in 1 minute...
freegpt35-1         | If this error persists, your country may not be supported yet.
freegpt35-1         | If your country was the issue, please consider using a U.S. VPN.
freegpt35-1         | Error refreshing session ID, retrying in 1 minute...
freegpt35-1         | If this error persists, your country may not be supported yet.
freegpt35-1         | If your country was the issue, please consider using a U.S. VPN.

**Comment by wbuntu** [comment]
> chatgpt-next-web-1 | [Server Config] using 1 of 1 api key chatgpt-next-web-1 | [Auth] use system api key chatgpt-next-web-1 | [Proxy] v1/chat/completions?path=v1&path=chat&path=completions chatgpt-next-web-1 | [Base Url] http://backend:8000 backend-1 | model='gpt-3.5-turbo' messages=[ChatMessage(role='system', content='\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2024/4/8 21:44:46\nLatex inline: x2 \nLatex block: e=mc2\n\n'), ChatMessage(role='user', content='我想让你担任机器学习工程师。我会写一些机器学习的概念，你的工作就是用通俗易懂的术语来解释它们。这可能包括提供构建模型的分步说明、给出所用的技术或者理论、提供评估函数等。我的问题是'), ChatMessage(role='user', content='hi')] temperature=1.0 top_p=1.0 max_length=None stream=True backend-1 | INFO: 172.31.0.5:50498 - "POST /v1/chat/completions?path=v1&path=chat&path=completions HTTP/1.1" 200 OK searxng-1 | 2024-04-08 13:44:45,093 ERROR:searx.engines.wikipedia: engine timeout searxng-1 | 2024-04-08 13:44:45,093 ERROR:searx.engines.wikidata: engine timeout searxng-1 | 2024-04-08 13:44:45,093 ERROR:searx.engines.duckduckgo: engine timeout searxng-1 | 2024-04-08 13:44:45,093 ERROR:searx.engines.google: engine timeout searxng-1 | 2024-04-08 13:44:45,093 ERROR:searx.engines.qwant: engine timeout searxng-1 | 2024-04-08 13:44:45,093 ERROR:searx.engines.brave: engine timeout freegpt35-1 | Request: POST /v1/chat/completions 1 messages (stream-enabled) searxng-1 | 2024-04-08 13:44:45,225 WARNING:searx.engines.wikipedia: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'en.wikipedia.org')) False searxng-1 | 2024-04-08 13:44:45,225 ERROR:searx.engines.wikipedia: HTTP requests timeout (search duration : 3.1328373439610004 s, timeout: 3.0 s) : ConnectTimeout searxng-1 | 2024-04-08 13:44:45,228 WARNING:searx.engines.brave: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'search.brave.com')) False searxng-1 | 2024-04-08 13:44:45,228 ERROR:searx.engines.brave: HTTP requests timeout (search duration : 3.135313393548131 s, timeout: 3.0 s) : ConnectTimeout searxng-1 | 2024-04-08 13:44:45,229 WARNING:searx.engines.duckduckgo: ErrorContext('searx/engines/duckduckgo.py', 118, 'res = get(query_url)', 'httpx.ConnectTimeout', None, (None, None, 'duckduckgo.com')) False searxng-1 | 2024-04-08 13:44:45,230 WARNING:searx.engines.qwant: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'api.qwant.com')) False searxng-1 | 2024-04-08 13:44:45,230 ERROR:searx.engines.duckduckgo: HTTP requests timeout (search duration : 3.137855425477028 s, timeout: 3.0 s) : ConnectTimeout searxng-1 | 2024-04-08 13:44:45,231 ERROR:searx.engines.qwant: HTTP requests timeout (search duration : 3.13800535351038 s, timeout: 3.0 s) : ConnectTimeout searxng-1 | 2024-04-08 13:44:45,231 WARNING:searx.engines.google: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)",'httpx.ConnectTimeout', None, (None, None, 'www.google.com')) False searxng-1 | 2024-04-08 13:44:45,231 ERROR:searx.engines.google: HTTP requests timeout (search duration : 3.138699973002076 s, timeout: 3.0 s) : ConnectTimeout searxng-1 | 2024-04-08 13:44:45,294 WARNING:searx.engines.wikidata: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.ConnectTimeout', None, (None, None, 'query.wikidata.org')) False searxng-1 | 2024-04-08 13:44:45,294 ERROR:searx.engines.wikidata: HTTP requests timeout (search duration : 3.2015139684081078 s, timeout: 3.0 s) : ConnectTimeout freegpt35-1 | Error refreshing session ID, retrying in 1 minute... freegpt35-1 | If this error persists, your country may not be supported yet. freegpt35-1 | If your country was the issue, please consider using a U.S. VPN. freegpt35-1 | Error refreshing session ID, retrying in 1 minute... freegpt35-1 | If this error persists, your country may not be supported yet. freegpt35-1 | If your country was the issue, please consider using a U.S. VPN.

这个需要部署后做下测试，仅ip属地支持免登录使用ChatGPT可以使用，可以看看文档里验证 chatgpt 接口的命令：https://github.com/wbuntu/images/tree/master/free-ask-internet
