### ISSUE TITLE
无法更改端口

### ISSUE THREAD

**Issue by mo957qx** [mikumaycry/images#2]
docker run -d --name free-ask-internet -p 3000:3000 --add-host=freegpt35:127.0.0.1 --add-host=backend:127.0.0.1 --add-host=searxng:127.0.0.1 wbuntu/free-ask-internet:v0.0.1

部署后，还是会监听在3000，可能代码里有个地方没有改

**Comment by wbuntu** [comment]
> docker run -d --name free-ask-internet -p 3000:3000 --add-host=freegpt35:127.0.0.1 --add-host=backend:127.0.0.1 --add-host=searxng:127.0.0.1 wbuntu/free-ask-internet:v0.0.1
> 
> 部署后，还是会监听在3000，可能代码里有个地方没有改

-p 3000:3000 是将宿主机的 3000 端口流量转发到容器的 3000 端口。
容器内现在固定是 3000 端口，宿主机上可以改自定义端口，例如 -p 8080:3000，将宿主机的 8080 端口流量转发到容器的 3000 端口
